version: "2"

services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile-dev
    image: nginx-dev
    container_name: nginx-dev
    ports:
      - "3000:80"
    links:
      - app
    volumes:
      - ./data/logs:/data/logs
    restart: always

  app:
    image: pushkinvk-dev
    container_name: pushkinvk-dev
    ports:
      - "3005:3005"
    links:
      - mongo
    volumes:
      - ./data:/data
    environment:
      - MONGO_URI=mongo
      - NODE_ENV=production
      - PORT=3005
      - ADMIN_EMAIL=222@ya.ru
      - ADMIN_PASSWORD=123
      # - SSL=TRUE
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    restart: always